site_name: XJU-Hurricane-docs
site_description: 新疆大学飓风战队文档站
site_url: https://xju-hurricane-team.github.io
repo_url: https://github.com/XJU-Hurricane-Team/xju-hurricane-team.github.io
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  font:
    # false # 国内网络访问 Google 源可能会有问题
    text: "Noto Sans SC - local"
    # code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)" # 检查用户系统配置是否为亮色
      scheme: default # 亮色模式
      primary: white # 基本颜色
      accent: blue # 按钮等互动块的颜色
      toggle:
        icon: material/eye
        name: 切换暗色模式
    - media: "(prefers-color-scheme: dark)" # 检查用户系统配置是否为暗色
      scheme: slate # 暗色模式
      primary: black # 基本颜色
      accent: blue # 按钮等互动块的颜色
      toggle:
        icon: material/eye-outline
        name: 切换亮色模式
  language: zh
  logo: img/logo-banner.png
  favicon: img/logo.png
  features:
    - content.code.copy # 代码块复制按钮
    - content.action.edit # 文章编辑按钮
    #- navigation.instant # Instant loading，像个单页应用
    - navigation.tracking # Anchor tracking
    - navigation.tabs # 导航栏
    - navigation.footer # 上一篇 / 下一篇导航按钮
    #- navigation.tabs.sticky # 导航栏不随页面滚动隐藏
    # - navigation.sections # 侧边栏分组显示
    #- navigation.expand # 导航栏自动展开
    - navigation.indexes # 组标题有专属页面
    - toc.follow # 目录自动跟随
    - navigation.top # 返回顶部按钮
    - search.suggest # 搜索推荐
    #- navigation.prune # 导航修剪，仅渲染可见链接，优化文档数量超过100的站点（实验），会导致页面间跳转速度变慢
    - search.highlight
  icon:
    repo: material/github
    #edit: material/pencil

plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      locale: zh
      date_format: '%Y-%m-%d'
  - git-authors:
      show_contribution: true
      avatar: true
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

extra:
  generator: false
  social:
    - name: Github
      link: https://github.com/XJU-Hurricane-Team
      icon: fontawesome/brands/github
    - name: Bilibili
      link: https://space.bilibili.com/522132031/
      icon: fontawesome/brands/bilibili
    - name: 微信公众号
      link: https://mp.weixin.qq.com/mp/qrcode?scene=10000004&size=102&__biz=MzkzNDYwNDAzMQ==&mid=2247483740&idx=1&sn=7d8b41e41cfe7f3100435bfbffd562e0&send_time=
      icon: fontawesome/brands/weixin

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition #MkDocs 警告框
  - footnotes #脚注
  - meta #自定义文章元数据
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
  - mdx_truly_sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/pangu@4.0.7/dist/browser/pangu.min.js
  - javascripts/mathjax.js #https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/latest.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js
  - javascripts/embed.js # https://viewer.altium.com/client/static/js/embed.js

extra_css:
  - stylesheets/extra.css

#############################################################
#############################################################
#############################################################

nav:
  - Home: index.md
  - About:
      - WELCOME COME TO HURRICANE!: About/index.md
      - 如何参与战队文档编辑: About/如何参与.md
      - 战队文档规范: About/文档规范.md
  - 电控:
      - 电控: Electrical/index.md
      - C语言:
          - C语言基础: https://deadline039.github.io/C/
          - C编码风格与规范: Electrical/C语言/C-code-style.md
      - STM32:
          - Stm32: Electrical/Stm32/index.md
          - Stm32开发:
            - Stm32简介: Electrical/Stm32/Stm32开发/Stm32简介.md
            - 系统架构: Electrical/Stm32/Stm32开发/系统架构.md
            - 启动过程: Electrical/Stm32/Stm32开发/启动过程.md
            - 项目组成: Electrical/Stm32/Stm32开发/项目组成.md
            - 开发环境: Electrical/Stm32/Stm32开发/开发环境.md
            - 调试工具: Electrical/Stm32/Stm32开发/调试工具.md
          - Stm32外设:
            - USART: Electrical/Stm32/Stm32外设/USART.md
            - IIC: Electrical/Stm32/Stm32外设/IIC.md
            - SPI: Electrical/Stm32/Stm32外设/SPI.md
            - CAN: Electrical/Stm32/Stm32外设/CAN.md
            - TIM: Electrical/Stm32/Stm32外设/TIM.md
      - RTOS:
          - FreeRTOS: Electrical/RTOS/FreeRTOS.md
      - Motors:
          - 电机简介: Electrical/Motors/index.md
          - 大疆电机: Electrical/Motors/大疆电机.md
          - 达妙电机: Electrical/Motors/达妙电机.md
          - 步进电机: Electrical/Motors/步进电机.md
          - VESC电机: Electrical/Motors/VESC电机.md
          - 宇树电机: Electrical/Motors/宇树电机.md
      - Lib:
        - MicroROS:
            - stm32运行microros: Electrical/Lib/MicroROS/stm32上运行microros/stm32上运行microros.md
            - 自定义消息+静态库: Electrical/Lib/MicroROS/自定义消息+静态库/自定义消息+静态库.md
            - 头文件功能分类: Electrical/Lib/MicroROS/头文件功能分类.md
            - 执行器管理: Electrical/Lib/MicroROS/执行器管理.md
        - TouchGFX:
            - TouchGFX: Electrical/Lib/TouchGFX/TouchGFX.md
      - 代码解析:
          - can_list: Electrical/代码解析/can_list解析.md
          - msg_protocol: Electrical/代码解析/msg_protocol解析.md
      - 控制理论:
          - 重新理解控制论: Electrical/ControlTheory/01-重新理解控制论.md
          - PID控制详解: Electrical/ControlTheory/02-PID控制.md
          - 机器人控制系统的分层设计与算法选型方法: Electrical/ControlTheory/03-机器人控制系统的分层设计与算法选型方法.md
          - LADRC快速上手: Electrical/ControlTheory/04-LADRC快速上手.md
          - LADRC代码实战: Electrical/ControlTheory/05-LADRC代码实战.md
      - 开发工具:
          - Segger:
            - SystemView: Electrical/Tools/Segger/SystemView配置指南.md
          - 电控基础: Electrical/Tools/电控基础.md
          - 树莓派: Electrical/Tools/树莓派.md
          - MCUViewer使用方法: Electrical/Tools/MCUViewer使用方法.md
  - 视觉:
      - 视觉: Vision/index.md
      - 导航:
        - 导航主线:
          - ROS2主流程: Vision/navigation/ROS2/导航_主线/ROS2主流程.md
          - Navigation2导航框架: Vision/navigation/ROS2/导航_主线/Navigation2导航框架.md
          - 北极熊Nav2框架: Vision/navigation/ROS2/导航_主线/北极熊Nav2框架.md
        - 导航支线:
          - 基础编程: Vision/navigation/ROS2/导航_支线/ROS2基础编程.md
          - 类的封装和调用: Vision/navigation/ROS2/导航_支线/类的封装和调用.md
          - Launch文件的编写: Vision/navigation/ROS2/导航_支线/launch文件的编写.md
          - 常用开发工具: Vision/navigation/ROS2/导航_支线/ROS2常用开发工具.md
        - 雷达定位:
          - Mid-360激光雷达配置教程: Vision/navigation/lidar/Mid-360激光雷达配置教程.md
          - 雷达定位信息: Vision/navigation/lidar/雷达定位信息.md
      - 深度学习:
        - 知识点: Vision/深度学习/知识点.md
        - yolo实践: Vision/深度学习/yolo实践.md
      - 强化学习:
          - 强化学习: Vision/强化学习/强化学习.md
          - 强化学习基础: Vision/强化学习/0.1强化学习基础.md
          - 马尔可夫决策过程: Vision/强化学习/0.2马尔可夫决策过程.md
          - 动态规划: Vision/强化学习/0.3动态规划.md
          - 无模型(评估): Vision/强化学习/0.4无模型(评估).md
          - 无模型控制(优化): Vision/强化学习/0.5无模型控制(优化).md
          - 价值函数近似: Vision/强化学习/0.6价值函数近似.md
          - 基于策略的强化学习: Vision/强化学习/0.7基于策略的强化学习.md
          - 贝尔曼方程: Vision/强化学习/1.贝尔曼方程.md
          - 蒙特卡洛期望: Vision/强化学习/2.蒙特卡洛期望.md
          - 随机近似(SA): Vision/强化学习/3.随机近似(SA).md
          - 时序差分: Vision/强化学习/4.时序差分.md
          - 值函数近似: Vision/强化学习/5.值函数近似.md
      - Tools:
          - X11Forwarding: Vision/Tools/x11转发远程服务桌面.md
          - 常用工具: Vision/Tools/常用工具.md
          - ROS工具: Vision/Tools/ROS工具.md
          - 双系统安装: Vision/Tools/双系统安装.md
      - 视觉复现:
          - 2025C: Vision/电赛/2025C.md
  - 机械:
      - 关于机械: Mechanical/index.md
      - 机械1:
          - 机械1-1: Mechanical/Mechanical1-1.md
          - 机械1-2: Mechanical/Mechanical1-2.md
      - 机械2:
          - 机械1-1: Mechanical/Mechanical1-1.md
          - 机械1-2: Mechanical/Mechanical1-2.md
      - 雕刻机的使用: Mechanical/雕刻机的使用.md
  - 电路:
      - 关于电路: Circuit/index.md
      - 教学 :
          - 零基础入门嘉立创: Circuit/教学/零基础入门嘉立创.md
          - LPKF ProtoLaser S4使用教程: Circuit/教学/LPKF打板机使用教程.md
      - RC主控 :
          - 2026F4: Circuit/RC主控/2026F4主控.md
          - 2026G4: Circuit/RC主控/2026G4主控.md
          - 2025F4: Circuit/RC主控/2025F4主控.md
      - 电驱:
          - FOC学习-硬件版: Circuit/电驱/FOC学习-硬件版.md
      - 电源:
          - MP5048并联大功率稳压电源: Circuit/电源/MP5048并联大功率稳压电源.md
          - MP4317宽负载双模式供电模块: Circuit/电源/MP4317宽负载双模式供电模块.md
      - 接线:
          - CAN & RS485接线: Circuit/接线/CAN & RS485接线.md
          - 滑环接线: Circuit/接线/滑环.md
      - 其他:
          - 常用外设引脚顺序: Circuit/其他/常用外设引脚顺序.md
          - 2026遥控器: Circuit/其他/2026遥控器.md
          - Daplink使用手册: Circuit/其他/Daplink使用手册.md
          - 单路气泵控制板: Circuit/其他/单路气泵控制板.md
          - XJU-ESP32开发板: Circuit/其他/xju-ESP32 1.0.md
          - 无线急停: Circuit/其他/xju_wireless-emergency-stop.md
  - 其它:
      - 关于其它: Other/index.md
      - 电池充放电: Other/电池冲放电.md
      - 电池过放急救指南: Other/电池过放急救指南.md
      - 战队共享文件连接: Other/战队共享文档连接教程.md
      - 打印机使用教程: Other/打印机使用教程.md
      - Jlink固件烧录教程: Other/Jlink固件烧录教程.md
  - 友链:
      - 友链: 友链/index.md
      - Deadline039's blog: https://deadline039.github.io/
      - PickingChip's blog: https://pickingchip.github.io/
